name: Manual Nightly Build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [ '1.20' ]
    name: Build
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Clone
        run: |
          git clone https://github.com/alist-org/alist

      - name: Install dependencies
        run: |
          sudo snap install zig --classic --beta
          docker pull crazymax/xgo:latest
          go install github.com/crazy-max/xgo@latest
          sudo apt install upx zip -y
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date +%F)" >> $GITHUB_ENV
          echo "HASH_CODE=$(date +%Y%m%d%H%M%S | md5sum | cut -b 1-8)" >> $GITHUB_ENV

      - name: Build
        run: |
          cd alist
          bash build.sh dev
          cd dist
          zip -q -r ../alist_Manual_${{ env.BUILD_TIME }}_${{ env.HASH_CODE }}.zip *

      - name: Uploading to GH-Release
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: "alist/alist_Manual_${{ env.BUILD_TIME }}_${{ env.HASH_CODE }}.zip"
          name: "Nightly_${{ env.BUILD_TIME }}_${{ env.HASH_CODE }}"
          tag: " alist_Nightly_${{ env.BUILD_TIME }}_${{ env.HASH_CODE }}"
          token: ${{ secrets.GITHUB_TOKEN }}
